package io.github.taills.common.jpa.repository.impl;

import io.github.taills.common.jpa.repository.SecurityIpAclRepositoryCustom;
import org.springframework.stereotype.Repository;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 * SecurityIpAcl 自定义Repository实现层
 *
 * @author automatically generated by taills's tool
 * @date 2022-01-17 20:16:59
 */
@Repository
public class SecurityIpAclRepositoryCustomImpl implements SecurityIpAclRepositoryCustom {

	@PersistenceContext
	private EntityManager em;
}
