spring:
  cache:
    type: simple
  main:
    lazy-initialization: false
    # 上面的为 true 时，swagger 不显示ApiModule
  mvc:
    hiddenmethod:
      filter:
        enabled: true #启用Restful 风格 的PUT DELETE 请求方式
    pathmatch:
      matching-strategy: ant_path_matcher
      # 没有上面这个配置的话，swagger 会异常，但据说无法正常使用 actuator
      # 参考 https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
  jpa:
    show-sql: false # 启用后，会在标准输出上输出sql语句
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}

  flyway:
    #是否开启flywary，默认true.
    enabled: true
    #当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false
    baseline-on-migrate: true
    #禁止清理数据
    clean-disabled: true
    #验证错误时是否清楚数据 当发现校验错误时是否自动调用clean，默认false
    clean-on-validation-error: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  task:
    scheduling:
      pool:
        size: 10
common:
  security:
    key: ZGdacn4IxhfzG9Td5Y99FlM1bIFNiE0k7PL7cuNLlTDMbGyEVh5a3WSijNhAMpfz9GSOAy6HaDVhAQoUG8YfqimX53zqFnUHY
    life-time: 86400
    mandatory-two-step-authentication: true
    two-setp-issuer: 淘宝
  # 24 小时

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: Common API
  application-version: 1.0
  group-name: ${swagger.application-name}
  application-description: ${swagger.application-name}
  contact:
    name: Taills
    email: taills@qq.com
    url: https://github.com/taills/


logging:
  level:
    root: WARN
    io:
      github:
        taills: DEBUG

