package io.github.taills.common.jpa.entity;

import io.github.taills.jpa.converter.InetAddressConverter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.Where;
import lombok.EqualsAndHashCode;
import lombok.Data;

import java.io.Serializable;
import java.net.InetAddress;


/**
 * IP 访问控制列表
 *
 * @author automatically generated by taills's tool
 * @date 2022-01-17 20:16:59
 */
@EqualsAndHashCode(callSuper = true)
@Data
@Entity
@Table(name = "security_ip_acl")
@Where(clause = "is_deleted = false")
@SQLDelete(sql = "update security_ip_acl set is_deleted = true where id = ?")
@ApiModel(value = "IP 访问控制列表")
public class SecurityIpAcl extends BaseEntity implements Serializable {

	/**
	 * 类型。 ALLOW/DENY
	 * nullable : true
	 * default  : 'ALLOW'
	 */
	@ApiModelProperty(value = "类型。 ALLOW/DENY")
	@Column(name = "acl_type", nullable = true)
	private String aclType;

	/**
	 * IP范围开始的地址
	 * nullable : false
	 * default  : null
	 */
	@ApiModelProperty(value = "IP范围开始的地址")
	@Column(name = "ip_range_begin", nullable = true, length = 16)
	@Convert(converter = InetAddressConverter.class)
	private String ipRangeBegin;

	/**
	 * IP范围结束的地址
	 * nullable : false
	 * default  : null
	 */
	@ApiModelProperty(value = "IP范围结束的地址")
	@Column(name = "ip_range_end", nullable = true, length = 16)
	@Convert(converter = InetAddressConverter.class)
	private String ipRangeEnd;

	/**
	 * 描述
	 * nullable : false
	 * default  : null
	 */
	@ApiModelProperty(value = "描述")
	@Column(name = "description", nullable = true, length = 128)
	private String description;
}
