package io.github.taills.common.jpa.service;

import io.github.taills.common.jpa.entity.SecurityIpAcl;
import io.github.taills.common.jpa.repository.SecurityIpAclRepository;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * SecurityIpAcl service层
 *
 * @author automatically generated by taills's tool
 * @date 2022-01-17 20:16:59
 */
@Service
public class SecurityIpAclService extends AbstractService<SecurityIpAcl, Integer> {

    @Resource
    private SecurityIpAclRepository rep;


    /**
     * 判断给定IP是否在 allow list 中
     *
     * @param ip
     * @return
     */
    public boolean inAllowList(String ip) {
        return rep.countInAllowList(ip) > 0;
    }

    /**
     * 判断给定IP是否在 deny list 中
     *
     * @param ip
     * @return
     */
    public boolean inDenyList(String ip) {
        return rep.countInDenyList(ip) > 0;
    }
}
