package io.github.taills.common.jpa.repository;

/**
 * SecurityIpAcl 自定义Repository层
 *
 * @author automatically generated by taills's tool
 * @date 2022-01-17 20:16:59
 */
public interface SecurityIpAclRepositoryCustom {

}
